# Generated by Django 5.1.2 on 2025-02-04 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("authentication", "0001_initial"),
        ("authentication", "0002_apiclient_token_apiclient_token_expiration"),
        ("authentication", "0003_remove_apiclient_name_alter_apiclient_client_secret_and_more"),
        ("authentication", "0004_alter_apiclient_token"),
        ("authentication", "0005_alter_apiclient_token_expiration"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "client_secret",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                ("token", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("token_expiration", models.FloatField(default=0)),
            ],
        ),
    ]
