# Generated by Django 5.2.1 on 2025-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclient",
            name="token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255, unique=True
            ),
        ),
    ]
