# Generated by Django 5.1.2 on 2025-02-04 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiclient",
            name="token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="token_expiration",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
