# Generated by Django 5.1.6 on 2025-02-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiclient",
            name="name",
        ),
        migrations.AddField(
            model_name="apiclient",
            name="token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="token_expiration",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="client_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
