# Generated by Django 5.1.6 on 2025-02-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("authentication", "0002_apiclient_token_apiclient_token_expiration"),
        ("authentication", "0003_remove_apiclient_name_alter_apiclient_client_secret_and_more"),
        ("authentication", "0004_alter_apiclient_token"),
        ("authentication", "0005_alter_apiclient_token_expiration"),
        ("authentication", "0006_alter_apiclient_client_secret_alter_apiclient_token"),
    ]

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiclient",
            name="name",
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="token_expiration",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="client_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="apiclient",
            name="token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
    ]
