# Generated by Django 5.1.2 on 2025-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_apiclient_token_apiclient_token_expiration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="apiclient",
            name="name",
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="client_secret",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
