# Generated by Django 5.1.2 on 2025-02-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_apiclient_name_alter_apiclient_client_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclient",
            name="token",
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
