# Generated by Django 5.1.2 on 2025-02-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_apiclient_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclient",
            name="token_expiration",
            field=models.FloatField(default=0),
        ),
    ]
