# Generated by Django 5.1.6 on 2025-02-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_apiclient_token_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiclient",
            name="client_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="apiclient",
            name="token",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
    ]
