build:
	npm run build

up:
	npm run dev

fresh:
	rm -rf node_modules/ package-lock.json
	npm install
	npm run dev

lint:
	npm run lint

clean:
	rm -rf dist/
	rm -rf html/
	rm -rf coverage/

storybook:
	npm run storybook

test:
	npm run test

update:
	npm run test:update