version: "3"

services:
  shopping-app-pgadmin:
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadminpass
    ports:
      - "5050:80"
    networks:
      - postgres-django-network
    restart: always
    secrets:
      - pgadminpass

  shopping-app-db:
    image: postgres:alpine3.18
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: /run/secrets/dbpass
      POSTGRES_DB: ${DJANGO_DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DJANGO_DATABASE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres-django-network
    restart: always
    secrets:
      - dbpass

  shopping-django-app:
    image: ghcr.io/evanlab02/shoppingappbe:${BACKEND_VERSION}
    environment:
      DJANGO_DATABASE_USER: ${DJANGO_DATABASE_USER}
      DJANGO_DATABASE_PASSWORD: /run/secrets/dbpass
      DJANGO_DATABASE_NAME: ${DJANGO_DATABASE_NAME}
      DJANGO_KEY: /run/secrets/djkey
      PROD_HOST: ${PROD_HOST}
    command:
      python -m uvicorn shoppingapp.configs.asgi:application --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      shopping-app-db:
        condition: service_healthy
    networks:
      - postgres-django-network
    restart: always
    secrets:
      - dbpass
      - djkey

  shopping-django-site:
    image: ghcr.io/evanlab02/shoppingappfe:${FRONTEND_VERSION}
    environment:
      DJANGO_KEY: /run/secrets/djkey
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      shopping-app-db:
        condition: service_healthy
    networks:
      - postgres-django-network
    restart: always
    secrets:
      - djkey

networks:
  postgres-django-network:
    driver: bridge

volumes:
  postgres-data:
    external: false

secrets:
  dbpass:
    file: ./secrets/dbpass.txt
  pgadminpass:
    file: ./secrets/pgadmin.txt
  djkey:
    file: ./secrets/djkey.txt