services:
  dev-shopping-app-pgadmin:
    container_name: shopping-pgadmin
    image: dpage/pgadmin4:8.5
    restart: always
    env_file:
      - .env.dev
    environment:
      SCRIPT_NAME: /pgadmin
    networks:
      - dev-postgres-django-network
    volumes:
      - dev-pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  dev-shopping-app-db:
    container_name: shopping-db
    image: postgres:16.2-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: postgres
    env_file:
      - .env.dev
    networks:
      - dev-postgres-django-network
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  dev-shopping-app-redis:
    image: redis:7.4.1-alpine3.20
    container_name: shopping-redis
    volumes:
      - dev-redis-data:/data
    networks:
      - dev-postgres-django-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  dev-shopping-django-administration:
    container_name: shopping-django-admin
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    env_file:
      - .env.dev
    networks:
      - dev-postgres-django-network
    depends_on:
      dev-shopping-app-db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  dev-shopping-django-app:
    container_name: shopping-django-app
    build:
      context: .
      dockerfile: docker/server/Dockerfile
    env_file:
      - .env.dev
    networks:
      - dev-postgres-django-network
    depends_on:
      dev-shopping-app-db:
        condition: service_healthy
    restart: always
    develop:
      watch:
        - action: sync+restart
          path: ./backend/authentication
          target: /backend/authentication
        - action: sync+restart
          path: ./backend/stores
          target: /backend/stores
        - action: sync+restart
          path: ./backend/items
          target: /backend/items
        - action: sync+restart
          path: ./backend/shoppingapp
          target: /backend/shoppingapp
        - action: rebuild
          path: ./backend/requirements.txt
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  dev-shopping-django-fe:
    container_name: shopping-django-fe-dev
    build:
      context: .
      dockerfile: docker/frontend/dev/Dockerfile
    env_file:
      - .env.dev
    networks:
      - dev-postgres-django-network
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync+restart
          path: ./frontend/vite.config.ts
          target: /app/vite.config.ts
        - action: rebuild
          path: ./frontend/package.json
          target: /app/package.json
        - action: rebuild
          path: ./frontend/package-lock.json
          target: /app/package-lock.json
        - action: sync
          path: ./frontend/src/
          target: /app/src/

  dev-shopping-django-site:
    container_name: shopping-django-site
    restart: always
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    expose:
      - "80"
    ports:
      - "8001:80"
    networks:
      - dev-postgres-django-network
    depends_on:
      dev-shopping-app-db:
        condition: service_healthy
    develop:
      watch:
        - action: sync+restart
          path: ./site/Caddyfile
          target: /etc/caddy/Caddyfile
        - action: sync+restart
          path: ./backend/static
          target: /var/www/html/static/
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

networks:
  dev-postgres-django-network:
    driver: bridge

volumes:
  dev-postgres-data:
    external: false
  dev-pgadmin-data:
    external: false
  dev-redis-data:
    external: false
