version: "3"

services:
  lite-shopping-app-be:
    build: .
    environment:
      DEFAULT_SETTINGS_MODULE: shoppingapp.settings.lite_settings
      LOCAL_DJANGO_KEY: ${LOCAL_DJANGO_KEY}
      LOCAL_DJANGO_HOST: ${LOCAL_DJANGO_HOST}
      SERVICE_PORT: ${SERVICE_PORT}
      TESTS_ENVIRONMENT: "True"
    command: python manage.py runserver 0.0.0.0:7001
    expose:
      - "7001"
    ports:
      - "7001:7001"
    networks:
      - dev-shopping-app-network
    restart: always

networks:
  dev-shopping-app-network:
    driver: bridge
