services:
  shopping-app-pgadmin:
    container_name: shopping-pgadmin
    image: dpage/pgadmin4:8.5
    env_file:
      - .env
    environment:
      SCRIPT_NAME: /pgadmin
    networks:
      - shopping-app-network
    restart: always
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M

  shopping-app-db:
    container_name: shopping-db
    image: postgres:16.2-alpine3.18
    environment:
      POSTGRES_USER: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - shopping-app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M

  shopping-django-administration:
    container_name: shopping-django-admin
    image: ghcr.io/evanlab02/shoppingappadmin:0.16.5
    env_file:
      - .env
    environment:
      SHOPPING_DEFAULT_SETTINGS_MODULE: shoppingapp.settings.settings
    command: /bin/bash -c "python manage.py migrate && python manage.py runserver"
    depends_on:
      shopping-app-db:
        condition: service_healthy
    networks:
      - shopping-app-network
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M

  shopping-django-app:
    container_name: shopping-django-app
    image: ghcr.io/evanlab02/shoppingappbe:0.16.5
    environment:
      SHOPPING_DEFAULT_SETTINGS_MODULE: shoppingapp.settings.settings
    env_file:
      - .env
    command: "gunicorn -b 0.0.0.0:80 -w 4 --log-config shoppingapp/logging.config --capture-output --log-level info --worker-class uvicorn_worker.UvicornWorker 'shoppingapp.config.asgi:app'"
    depends_on:
      shopping-app-db:
        condition: service_healthy
    networks:
      - shopping-app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M

  shopping-django-site:
    container_name: shopping-django-site
    image: ghcr.io/evanlab02/shoppingappsite:0.16.5
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      shopping-app-db:
        condition: service_healthy
    networks:
      - shopping-app-network
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4096M

networks:
  shopping-app-network:
    driver: bridge

volumes:
  postgres-data:
    external: false
  pgadmin-data:
    external: false
