version: "3"

services:
  dev-shopping-app-db:
    image: postgres:alpine3.18
    expose:
      - "5432"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DEV_DATABASE_USER}
      POSTGRES_PASSWORD: ${DEV_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE_NAME}
    volumes:
      - dev-shopping-app-db-data:/var/lib/postgresql/data
    networks:
      - dev-shopping-app-network
    restart: always

  dev-shopping-app-be:
    build: .
    environment:
      DEFAULT_SETTINGS_MODULE: shoppingapp.settings.dev_settings
      DEV_DATABASE_USER: ${DEV_DATABASE_USER}
      DEV_DATABASE_PASSWORD: ${DEV_DATABASE_PASSWORD}
      DEV_DATABASE_NAME: ${DEV_DATABASE_NAME}
      DEV_DJANGO_KEY: ${DEV_DJANGO_KEY}
      DEV_DJANGO_HOST: ${DEV_DJANGO_HOST}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DEV_DB_PORT: ${DEV_DB_PORT}
      SERVICE_PORT: ${SERVICE_PORT}
    command: python manage.py runserver 0.0.0.0:7001
    expose:
      - "7001"
    ports:
      - "7001:7001"
    networks:
      - dev-shopping-app-network
    restart: always

networks:
  dev-shopping-app-network:
    driver: bridge

volumes:
  dev-shopping-app-db-data:
    external: false
