version: "3"

services:
  dev-shopping-app-be:
    build: .
    environment:
      DEFAULT_SETTINGS_MODULE: shoppingapp.settings.lite_settings
      DEV_DATABASE_USER: ${DEV_DATABASE_USER}
      DEV_DATABASE_PASSWORD: ${DEV_DATABASE_PASSWORD}
      DEV_DATABASE_NAME: ${DEV_DATABASE_NAME}
      DEV_DJANGO_KEY: ${DEV_DJANGO_KEY}
      DEV_DJANGO_HOST: ${DEV_DJANGO_HOST}
      DEV_DB_HOST: ${DEV_DB_HOST}
      DEV_DB_PORT: ${DEV_DB_PORT}
      SERVICE_PORT: ${SERVICE_PORT}
    command: shoppingapp
    expose:
      - "7001"
    ports:
      - "7001:7001"
    networks:
      - dev-shopping-app-network
    restart: always

networks:
  dev-shopping-app-network:
    driver: bridge

