# Generated by Django 5.1.2 on 2025-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingstore",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="shoppingstore",
            name="store_type",
            field=models.IntegerField(
                choices=[(1, "Online"), (2, "In-Store"), (3, "Both")], db_index=True
            ),
        ),
    ]
