site_name: Shopping List App
site_url: https://evanlab02.github.io/ShoppingListApp/
repo_url: https://github.com/evanlab02/ShoppingListApp
repo_name: ShoppingListApp

extra:
  version:
    provider: mike

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"

theme:
  name: material
  features:
    - content.code.copy
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.prune
    - navigation.path
    - navigation.top
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Getting Started:
    - Home: index.md
    - Installation: start.md
    - Configuration: config.md
  - Admin:
    - Getting Started: admin/index.md
    - Items: admin/items.md
  - API:
    - Getting Started: api/index.md
    - Stores:
      - /api/v1/stores/types/mapping: api/v1/stores/types/mapping.md
      - /api/v1/stores/aggregate/search: api/v1/stores/aggregate/search.md
    - Additional Resources:
      - Error Handling: api/errors.md
  - Developers/Contributors:
    - Getting Started: dev/index.md
    - Error Handling: dev/errors.md
  - Reporting Bugs: bugs.md
