site_name: Shopping List App
plugins:
  - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - "pymdownx.inlinehilite"
  - "pymdownx.snippets"
  - "pymdownx.superfences"
  - "admonition"
  - "pymdownx.details"
  - "pymdownx.superfences"
theme:
  name: material
  features:
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - Getting Started: start.md
  - User Guides:
    - Logging in: web/index.md
    - Dashboard: web/dashboard.md
    - Items: web/items.md
    - Stores: web/stores.md
  - Admin Guides: 
    - Reset API Client: admin/index.md
  - Consuming the API:
    - Creating your token: api/index.md
    - Consuming the API: api/consume.md
  - Architecture and code: 
    - Overview: code/index.md
