name: Build

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read



jobs:
  static-files-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: ""
          filenames: |
            .env.template
          quiet: false
          if-file-not-found: error
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Setup
        run: |
          pip install -r requirements.txt
      - name: Create/Build Static Files
        run: |
          python manage.py collectstatic --no-input

  assets-files-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.20.4"
          cache: 'npm'
      - name: Setup
        run: |
          npm ci
      - name: Create/Build FE assets
        run: |
          npm run build

  docker-images-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Images
        run: |
          docker build -f docker/admin/Dockerfile -t shopping-app .
          docker build -f docker/server/Dockerfile -t shopping-app-admin .
          docker build -f docker/site/Dockerfile -t shopping-app-site .