name: Build

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

defaults:
  run:
    working-directory: src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: ""
          filenames: |
            .env.template
          quiet: false
          if-file-not-found: error
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Setup
        run: |
          pip install -r requirements.txt
      - name: Create/Build Static Files
        run: |
          python manage.py collectstatic --no-input
      - name: Build Docker Images
        working-directory: .
        run: |
          docker build -f docker/admin/Dockerfile -t shopping-app .
          docker build -f docker/server/Dockerfile -t shopping-app-admin .
          docker build -f docker/site/Dockerfile -t shopping-app-site .
