name: Build

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  lint-and-docs-styling:
    runs-on: ubuntu-latest

    # Do not use any sensitve values within in the variables. Should only contain test values.
    env:
      DEV_DJANGO_KEY: ${{ vars.CI_DJANGO_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        run: |
          pip install -r requirements-dev.txt
      - name: Create/Build Static Files
        run: |
          python manage.py collectstatic --noinput --settings=shoppingapp.settings.local_settings
      - name: Build Docker Image
        run: |
          docker build -t shoppingapp .
