name: Lint and Docs Styling

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  lint-and-docs-styling:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup
        run: |
          pip install -r requirements-dev.txt
      - name: Lint and Docs Styling
        working-directory: ./src/
        run: |
          black . --check
          isort . --check-only --profile black
          flake8 . --max-line-length=100
          pydocstyle .
