name: Lint and Docs Styling

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read



jobs:
  be-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Setup
        run: |
          pip install -r requirements-dev.txt
      - name: Lint and Docs Styling
        run: |
          black . --check
          isort . --check-only --profile black
          flake8 . --max-line-length=100
          mypy . --strict

  fe-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.20.4"
          cache: 'npm'
      - name: Setup
        run: |
          npm ci
      - name: Lint and Docs Styling
        run: |
          npm run lint