on:
  push:
    branches:
      - trunk

permissions:
  contents: write
  pull-requests: write

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: ShoppingListApp
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: trunk
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
        with:
          fetch-depth: 0
      - name: Create App Zip
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          mkdir ShoppingListApp
          cp -r maintenance compose.yml Makefile setup.sh ShoppingListApp
          zip -r ShoppingListApp.zip ShoppingListApp
      - name: Upload App Zip
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} ShoppingListApp.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
