on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

  admin:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build App Image
        run: |
          docker build -f docker/admin/Dockerfile -t shopping-admin:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Create Tags
        run: |
          docker tag shopping-admin:latest ghcr.io/evanlab02/shopping-admin:latest
          docker tag shopping-admin:latest ghcr.io/evanlab02/shopping-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      - name: Push Tags
        run: |
          docker push ghcr.io/evanlab02/shopping-admin:latest
          docker push ghcr.io/evanlab02/shopping-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

  app:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build App Image
        run: |
          docker build -f docker/app/Dockerfile -t shopping-app:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Create Tags
        run: |
          docker tag shopping-app:latest ghcr.io/evanlab02/shopping-app:latest
          docker tag shopping-app:latest ghcr.io/evanlab02/shopping-app:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      - name: Push Tags
        run: |
          docker push ghcr.io/evanlab02/shopping-app:latest
          docker push ghcr.io/evanlab02/shopping-app:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

  web:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Web Image
        run: |
          docker build -f docker/web/Dockerfile -t shopping-web:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Create Tags
        run: |
          docker tag shopping-web:latest ghcr.io/evanlab02/shopping-web:latest
          docker tag shopping-web:latest ghcr.io/evanlab02/shopping-web:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
      - name: Push Tags
        run: |
          docker push ghcr.io/evanlab02/shopping-web:latest
          docker push ghcr.io/evanlab02/shopping-web:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}

  static:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Zip Static Files
        run: |
          zip -r static.zip static/
      - name: Upload Static Files
        run:
          gh release upload ${{ needs.release-please.outputs.tag_name }} static.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  caddyfile:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload Caddyfile
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} Caddyfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "docs/requirements.txt"
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt
      - name: Sync Changes
        run: |
          git fetch
      - name: Deploy Documentation
        run: |
          uv run mike deploy --push --update-aliases ${{ needs.release-please.outputs.tag_name }} latest
          uv run mike set-default --push latest
