on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: ShoppingListApp-Backend
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: trunk

  release-backend:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -f docker/server/Dockerfile -t shoppinglistapp-backend:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} .
          docker build -f docker/server/Dockerfile -t shoppinglistapp-backend:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          docker tag shoppinglistapp-backend:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} ghcr.io/evanlab02/shoppingappbe:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/evanlab02/shoppingappbe:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag shoppinglistapp-backend:latest ghcr.io/evanlab02/shoppingappbe:latest
          docker push ghcr.io/evanlab02/shoppingappbe:latest
  
  release-admin:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          docker build -f docker/admin/Dockerfile -t shoppinglistapp-admin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} .
          docker build -f docker/admin/Dockerfile -t shoppinglistapp-admin:latest .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          docker tag shoppinglistapp-admin:${{needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }} ghcr.io/evanlab02/shoppingappadmin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker push ghcr.io/evanlab02/shoppingappadmin:${{ needs.release-please.outputs.major }}.${{ needs.release-please.outputs.minor }}.${{ needs.release-please.outputs.patch }}
          docker tag shoppinglistapp-admin:latest ghcr.io/evanlab02/shoppingappadmin:latest
          docker push ghcr.io/evanlab02/shoppingappadmin:latest

  release-static:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Zip static
        run: |
          zip -r static.zip src/static
      - name: Upload static
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} static.zip

  release-coverage:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: aarcangeli/load-dotenv@v1.0.0
        with:
          path: ""
          filenames: |
            .env.template
          quiet: false
          if-file-not-found: error
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Setup
        working-directory: src/
        run: |
          pip install -r requirements-dev.txt
      - name: Create Migrations
        working-directory: src/
        run: |
          python manage.py makemigrations
      - name: Run Migrations
        working-directory: src/
        run: |
          python manage.py migrate
      - name: Run Tests
        working-directory: src/
        run: |
          pytest . --cov=. --cov-report term-missing -n auto
      - name: Generate coverage report
        working-directory: src/
        run: |
          coverage html
      - name: Zip coverage report
        working-directory: src/
        run: |
          zip -r coverage.zip htmlcov
      - name: Upload coverage report
        working-directory: src/
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} coverage.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
