on:
  push:
    branches:
      - trunk

permissions: write-all

name: Release Please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: simple
          package-name: ShoppingListApp-Backend
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: trunk
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Build Docker Image
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          docker build -f docker/server/Dockerfile -t shoppinglistapp-backend:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} .
          docker build -f docker/server/Dockerfile -t shoppinglistapp-backend:latest .
          docker build -f docker/admin/Dockerfile -t shoppinglistapp-admin:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} .
          docker build -f docker/admin/Dockerfile -t shoppinglistapp-admin:latest .
      - name: Log in to registry
        if: ${{ steps.release.outputs.releases_created }}
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          docker tag shoppinglistapp-backend:${{steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} ghcr.io/evanlab02/shoppingappbe:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker push ghcr.io/evanlab02/shoppingappbe:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker tag shoppinglistapp-backend:latest ghcr.io/evanlab02/shoppingappbe:latest
          docker push ghcr.io/evanlab02/shoppingappbe:latest
          docker tag shoppinglistapp-admin:${{steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} ghcr.io/evanlab02/shoppingappadmin:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker push ghcr.io/evanlab02/shoppingappadmin:${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
          docker tag shoppinglistapp-admin:latest ghcr.io/evanlab02/shoppingappadmin:latest
          docker push ghcr.io/evanlab02/shoppingappadmin:latest
