name: Tests and Sonarcloud

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  tests-and-sonarcloud:
    runs-on: ubuntu-latest

    env:
      DEV_DJANGO_KEY: ${{ vars.CI_DJANGO_KEY }}
      DEV_DJANGO_DATABASE_USER: ${{ vars.CI_DJANGO_DATABASE_USER }}
      DEV_DJANGO_DATABASE_PASSWORD: ${{ vars.CI_DJANGO_DATABASE_PASSWORD }}
      DEV_DJANGO_DATABASE_NAME: ${{ vars.CI_DJANGO_DATABASE_NAME }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Start Develop DB
        run: |
          docker-compose up -d --build
      - name: Setup
        run: |
          pip install -r requirements-dev.txt
      - name: Create Migrations
        run: |
          python manage.py makemigrations --settings=shoppingapp.settings.test_settings
      - name: Run Migrations
        run: |
          python manage.py migrate --settings=shoppingapp.settings.test_settings
      - name: Run Tests
        run: |
          pytest -v --cov=. --cov-report term-missing
      - name: Generate Coverage Report
        run: |
          coverage xml
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
